[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/"
  to = "/es"
  status = 302
  force = false
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/"
  status = 200